### PR TITLE
Fix exe other-modules containing dots

### LINKED ISSUE #17: Executables with `other-modules` end up with incorrect paths
I have:

```cabal
executable analyse-quoting
  ...
  other-modules:
    CircuitHub.Quoting.Analysis.AssemblyPricing.Picofactory2
    CircuitHub.Quoting.Analysis.CompetitorQuote
    CircuitHub.Quoting.Analysis.FinalOffers
    CircuitHub.Quoting.Analysis.QuoteParameters
    CircuitHub.Quoting.Analysis.Report
    CircuitHub.Quoting.Analysis.Sample
```

But when I run `gen-hie` I get:

```yaml
    - path: "./quoting/exe-analyse-quoting/Main.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.AssemblyPricing.Picofactory2.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.CompetitorQuote.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.FinalOffers.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.QuoteParameters.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.Report.hs"
      component: "quoting:exe:analyse-quoting"

    - path: "./quoting/exe-analyse-quoting/CircuitHub.Quoting.Analysis.Sample.hs"
      component: "quoting:exe:analyse-quoting"
```

Which is wrong - these files don't exist.

### PR DESCRIPTION
**Pull request by jneira**
* Fixes #17

### CODE REVIEW

File: src/Hie/Cabal/Parser.hs [hunk 1]
```diff
@@ -121,9 +121,10 @@ pathMain i p m o a =
     <|> (skipBlockLine i >> pathMain i p m o a)
     <|> pure
       ( map (<//> m) p
-          <> [ p' <//> (o' <> ".hs")
+          <> [ p' <//> (o'' <> ".hs")
                | p' <- p,
-                 o' <- filter (`notElem` a) o
+                 o' <- filter (`notElem` a) o,
+                 let o'' = T.replace "." "/" o'
```
Comment (fendor) [inline src/Hie/Cabal/Parser.hs:127]: Is that platform independent? So, works on windows?

Comment (jneira) [reply src/Hie/Cabal/Parser.hs:127]: Yeah, i hope so or it will not work for me 😄 
well, `hie.yaml` uses unix paths in the config and it works, right?, but i will check just in case

Comment (fendor) [reply src/Hie/Cabal/Parser.hs:127]: You are right, those paths get normalised before usage, iirc.

**Review by fendor — APPROVED** [review]
LGTM!

**Review by Avi-D-coder — APPROVED** [review]

**Comment by jneira** [comment]
I've checked a hls version with this patch in windows and it works, so merging

**Comment by jneira** [comment]
@Avi-D-coder could we publish a hackage version with the fix?

**Comment by Avi-D-coder** [comment]
Will do
